language: python
env:
    TRAVISBUG="#1027"
matrix:
    exclude:
        - env: TRAVISBUG="#1027"
    include:
        - python: "2.7"
          env: BUILDENV=precise
        - python: "2.7"
          env: BUILDENV=latest
        - python: "pypy"
          env: BUILDENV=latest
    allow_failures:
        - python: "pypy"
          env: BUILDENV=latest
install:
    - pip install -r .travis/requirements-$BUILDENV.txt
    - pip install pep8 --use-mirrors
    - pip install https://github.com/dcramer/pyflakes/tarball/master
    - pip install -q -e . --use-mirrors
script:
    - trial scrapyd
notifications:
    irc:
        channels:
            - "irc.freenode.org#tomahawk.charts"
        use_notice: true
        skip_join: true
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 scraper"
  - pyflakes -x W scraper
